const mergedCatalogData = {
  "Oleaginosas": [
      "Amêndoa defumada",
      "Amêndoa laminada",
      "Amêndoas",
      "Avelã",
      "Castanha brejeira",
      "Castanha brejeira extra",
      "Castanha crua",
      "Castanha quebradinha",
      "Castanha-do-pará inteira",
      "Noz mariposa",
      "Noz pecan",
      "Pistache com casca",
      "Pistache sem casca",
      "Amendoim Japonês - salsa e cebola",
      "Amendoim Japonês - pimenta",
      "Amendoim Japonês - churrasco",
      "Amendoim Japonês - tradicional",
      "Amendoim com casca cru",
      "Amendoim com casca torrado",
      "Amendoim doce",
      "Amendoim runner",
      "Amendoim banda com sal",
      "Amendoim banda sem sal",
      "Mix nuts"
  ],
  "Farinhas": [
      "Farinha de amêndoa",
      "Farinha de arroz branca",
      "Farinha de banana",
      "Farinha de batata-doce",
      "Farinha de beterraba",
      "Farinha de castanha",
      "Farinha de chia",
      "Farinha de coco",
      "Farinha de grão-de-bico",
      "Farinha de linhaça dourada",
      "Farinha de linhaça marrom",
      "Farinha de maçã",
      "Farinha de maracujá",
      "Farinha de quinoa",
      "Farinha de uva",
      "Açaí em pó",
      "Açúcar de coco",
      "Agar Agar",
      "Albumina",
      "Farinha de amendoim",
      "Bicarbonato",
      "Aveias (farinha)",
      "Aveias (farelo)",
      "Aveias (flocos finos)",
      "Aveias (flocos grossos)",
      "Cacau black",
      "Cacau 70%",
      "Catuaba em pó",
      "Clorella pó",
      "Colágeno Hidrolisado",
      "Erytritol",
      "Fécula de batata",
      "Gelatina sem sabor",
      "Ginko biloba",
      "Ginseng",
      "Goma xantana",
      "Guaraná em pó",
      "Leite de coco em pó",
      "Levedo de cerveja",
      "Levedura nutricional",
      "Maca peruana (tradicional)",
      "Maca peruana (black)",
      "Matcha gengibre mel e mostarda",
      "Spirulina",
      "Taurina",
      "Tribulus Terrestre",
      "Xilitol"
  ],
  "Grãos": [
      "Grão-de-bico",
      "Arroz negro",
      "Arroz vermelho",
      "Lentilha",
      "Soja em grão",
      "Quinoa branca",
      "Quinoa preta",
      "Quinoa vermelha",
      "Café em grão",
      "Café verde em grão",
      "Chia",
      "Feijão azuki",
      "Feijão moyashi",
      "Flocos de milho com açúcar",
      "Flocos de milho sem açúcar",
      "Feno grego",
      "Funghi seco",
      "Gergelim branco",
      "Gergelim preto",
      "Gergelim com casca",
      "Gotas de chocolate ao leite",
      "Gotas de chocolate branco",
      "Granola tradicional",
      "Granola com banana",
      "Granola diet",
      "Linhaça dourada",
      "Linhaça marrom",
      "Mix gergelim",
      "Pepita girassol",
      "Pepita abóbora",
      "Sagu"
  ],
  "Temperos": [
      "Alecrim",
      "Alho desidratado em pó",
      "Alho desidratado frito",
      "Bacon bits",
      "Bacon em pó",
      "Coentro (grão)",
      "Coentro (moído)",
      "Cominho (grão)",
      "Cominho moído com pimenta",
      "Cúrcuma moída",
      "Curry",
      "Cebola em pó",
      "Cebola crisp",
      "Cebola roxa",
      "Cebola desidratada",
      "Erva-doce pó",
      "Gengibre em pó",
      "Louro (folha)",
      "Louro (pó)",
      "Manjericão",
      "Mostarda (grão)",
      "Mostarda moída",
      "Noz-moscada (grão)",
      "Noz-moscada (pó)",
      "Orégano",
      "Páprica defumada",
      "Páprica doce",
      "Páprica picante",
      "Pimenta calabresa",
      "Pimenta jamaica",
      "Pimenta malagueta",
      "Pimenta chilli",
      "Pimenta caiena",
      "Pimenta-do-reino branca moída",
      "Pimenta-do-reino grão/preta",
      "Pimenta-do-reino grão/moída",
      "Ajiomoto",
      "Alho cabeça roxo",
      "Amaciante de carne",
      "Chimichurry com pimenta",
      "Chimichurry sem pimenta",
      "Chimichurry alho frito",
      "Chimigaleto",
      "Colorau",
      "Conquista sogra",
      "Creme de cebola",
      "Lemon pepper",
      "Lemon pepper defumado",
      "Limão com orégano",
      "Limão em pó",
      "Mix pimenta",
      "Molho tártaro",
      "Orange pepper",
      "Sal parrilha",
      "Sal vegano",
      "Flor de sal",
      "Sal himalaia fino",
      "Sal himalaia grosso",
      "Salsa",
      "Salsa, cebola e bacon",
      "Salsa, cebola e alho",
      "Tempero Foundor",
      "Tempera Tudo",
      "Tempero Ana Maria",
      "Tempero Baiano",
      "Tempero Bife Acebolado",
      "Tempero Caipira",
      "Tempero da Esposa",
      "Tempero da Família",
      "Tempero da Fazenda",
      "Tempero da Vó",
      "Tempero do Chef",
      "Tempero do Pai",
      "Tempero Dry Rub",
      "Tempero Edu Guedes",
      "Tempero Feijão",
      "Tempero Fit Carne",
      "Tempero Fit Frango",
      "Tempero Natural",
      "Tempero Gourmet",
      "Tempero para Paella",
      "Tempero Pega Marido",
      "Tempero Sírio",
      "Tempero Vinagrete"
  ],
  "Chás": [
      "Boldo",
      "Chá verde",
      "Hibisco flor",
      "Matcha em pó",
      "Amora miura",
      "Casca de noz pecan",
      "Chá verde"
  ],
  "Especiarias para Drinks": [
      "Anis estrelado",
      "Canela em pau",
      "Cardamomo",
      "Cravo-da-índia",
      "Hibisco flor",
      "Limão em pó",
      "Zimbro",
      "Anis estrelado",
      "Canela em pau",
      "Canela em pó",
      "Laranja desidratada rodela"
  ],
  "Petiscos": [
    "Chips de banana salgado",
    "Chips de banana com canela",
    "Chips de macaxeira lemon pepper",
    "Chips de macaxeira defumada",
    "Chips de macaxeira tradicional",
    "Chips de batata doce tradicional",
    "Chips de batata doce lemon pepper",
    "Chips de queijo provolone tradicional",
    "Chips de queijo provolone com goiabada",
    "Chips de queijo coalho tradicional",
    "Chips de queijo coalho com goiaba",
    "Chips de queijo coalho com nutella",
    "Chips de queijo parmesão",
    "Chips de queijo do reino tradicional",
    "Chips de queijo do reino com goiabada",
    "Ervilha com wassabi",
    "Fava torrada mostarda e mel",
    "Grão de bico torrado com mostarda e mel",
    "Milho espanhol mostarda e mel",
    "Mix coquetel",
    "Snack (cebola)",
    "Snack (queijo)",
    "Snack (bbq)"
  ],
  "Frutas": [
    "Ameixa sem caroço",
    "Amora muira",
    "Blueberry",
    "Cranberry",
    "Damasco",
    "Laranja desidratada",
    "Maçã (rodelas)",
    "Maçã (farinha)",
    "Pera metades",
    "Tâmara jumbo",
    "Tâmara sem caroço",
    "Uva passa branca",
    "Uva passa preta",
    "Chips de coco",
    "Coco caramelizado",
    "Frutas cristalizadas"
  ]
};

export default mergedCatalogData;