const mergedCatalogData = {
  "Oleaginosas": [
      "Amêndoa defumada",
      "Amêndoa laminada",
      "Amêndoas",
      "Avelã",
      "Castanha brejeira",
      "Castanha brejeira extra",
      "Castanha crua",
      "Castanha quebradinha",
      "Castanha-do-pará inteira",
      "Noz mariposa",
      "Noz pecan",
      "Pistache com casca",
      "Pistache sem casca",
      "Amendoim Japonês (salsa e cebola, pimenta, churrasco e tradicional)",
      "Amendoim com casca (cru e torrado)",
      "Amendoim doce",
      "Amendoim runner",
      "Amendoim banda (com sal e sem)",
      "Mix nuts"
  ],
  "Farinhas": [
      "Farinha de amêndoa",
      "Farinha de arroz branca",
      "Farinha de banana",
      "Farinha de batata-doce",
      "Farinha de beterraba",
      "Farinha de castanha",
      "Farinha de chia",
      "Farinha de coco",
      "Farinha de grão-de-bico",
      "Farinha de linhaça dourada",
      "Farinha de linhaça marrom",
      "Farinha de maçã",
      "Farinha de maracujá",
      "Farinha de quinoa",
      "Farinha de uva",
      "Açaí em pó",
      "Açúcar de coco",
      "Agar Agar",
      "Albumina",
      "Farinha de amendoim",
      "Bicarbonato",
      "Aveias (farinha, farelo, flocos finos e flocos grossos)",
      "Cacau black",
      "Cacau 70%",
      "Catuaba em pó",
      "Clorella pó",
      "Colágeno Hidrolisado",
      "Erytritol",
      "Fécula de batata",
      "Gelatina sem sabor",
      "Ginko biloba",
      "Ginseng",
      "Goma xantana",
      "Guaraná em pó",
      "Leite de coco em pó",
      "Levedo de cerveja",
      "Levedura nutricional",
      "Maca peruana (tradicional ou black)",
      "Matcha gengibre mel e mostarda",
      "Spirulina",
      "Taurina",
      "Tribulus Terrestre",
      "Xilitol"
  ],
  "Grãos": [
      "Grão-de-bico",
      "Arroz negro",
      "Arroz vermelho",
      "Lentilha",
      "Soja em grão",
      "Quinoa branca",
      "Quinoa preta",
      "Quinoa vermelha",
      "Café em grão",
      "Café verde em grão",
      "Chia",
      "Feijão azuki",
      "Feijão moyashi",
      "Flocos de milho (com açúcar ou sem)",
      "Feno grego",
      "Funghi seco",
      "Gergelim (branco, preto e com casca)",
      "Gotas de chocolate ao leite",
      "Gotas de chocolate branco",
      "Granola (tradicional, com banana e diet)",
      "Linhaça (dourada e marrom)",
      "Mix gergelim",
      "Pepita (girassol ou abóbora)",
      "Sagu"
  ],
  "Temperos": [
      "Alecrim",
      "Alho desidratado, em pó ou frito",
      "Bacon bits",
      "Bacon em pó",
      "Coentro (grão ou moído)",
      "Cominho (grão, moído ou com pimenta)",
      "Cúrcuma moída",
      "Curry",
      "Cebola (em pó, crisp, roxa e desidratada)",
      "Erva-doce pó",
      "Gengibre em pó",
      "Louro (folha ou pó)",
      "Manjericão",
      "Mostarda (grão ou moída)",
      "Noz-moscada (grão ou pó)",
      "Orégano",
      "Páprica (defumada, doce ou picante)",
      "Pimenta (calabresa, jamaica, malagueta, chilli e caiena)",
      "Pimenta-do-reino (branca moída ou grão/preta grão ou moída)",
      "Ajiomoto",
      "Alho cabeça roxo",
      "Amaciante de carne",
      "Chimichurry (com pimenta, sem pimenta e alho frito)",
      "Chimigaleto",
      "Colorau",
      "Conquista sogra",
      "Creme de cebola",
      "Lemon pepper",
      "Lemon pepper defumado",
      "Limão com orégano",
      "Limão em pó",
      "Mix pimenta",
      "Molho tártaro",
      "Orange pepper",
      "Sal (parrilha ou vegano)",
      "Flor de sal",
      "Sal himalaia (fino ou grosso)",
      "Salsa",
      "Salsa, cebola e bacon",
      "Salsa, cebola e alho",
      "Tempero Foundor",
      "Tempera Tudo",
      "Tempero Ana Maria",
      "Tempero Baiano",
      "Tempero Bife Acebolado",
      "Tempero Caipira",
      "Tempero da Esposa",
      "Tempero da Família",
      "Tempero da Fazenda",
      "Tempero da Vó",
      "Tempero do Chef",
      "Tempero do Pai",
      "Tempero Dry Rub",
      "Tempero Edu Guedes",
      "Tempero Feijão",
      "Tempero Fit Carne",
      "Tempero Fit Frango",
      "Tempero Natural",
      "Tempero Gourmet",
      "Tempero para Paella",
      "Tempero Pega Marido",
      "Tempero Sírio",
      "Tempero Vinagrete"
  ],
  "Chás": [
  "Boldo",
  "Chá verde",
  "Hibisco flor",
  "Matcha em pó",
  "Amora miura",
  "Casca de noz pecan",
  "Chá verde"
  ],
  "Especiarias para Drinks": [
    "Anis estrelado",
    "Canela em pau",
    "Cardamomo",
    "Cravo-da-índia",
    "Hibisco flor",
    "Limão em pó",
    "Zimbro",
    "Anis estrelado",
    "Canela (em pau ou em pó)",
    "Laranja desidratada rodela"
  ],
  "Petiscos": [
    "Chips de banana (salgado ou com canela)",
    "Chips de macaxeira (lemon pepper, defumada ou tradicional)",
    "Chips de batata doce (Tradicional ou lemon pepper)",
    "Chips de queijo provolone (tradicional ou com goiabada)",
    "Chips de queijo coalho (Tradicional, com goiaba ou nutella)",
    "Chips de queijo parmesão",
    "Chips de queijo do reino (tradicional ou com goiabada)",
    "Ervilha com wassabi",
    "Fava torrada mostarda e mel",
    "Grão de bico torrado com mostarda e mel",
    "Milho espanhol mostarda e mel",
    "Mix coquetel",
    "Snack (cebola, queijo e bbq)"
  ],
  "Frutas": [
    "Ameixa sem caroço",
    "Amora muira",
    "Blueberry",
    "Cranberry",
    "Damasco",
    "Laranja desidratada",
    "Maçã (rodelas ou farinha)",
    "Pera metades",
    "Tâmara (jumbo ou sem caroço)",
    "Uva passa (branca ou preta)",
    "Chips de coco",
    "Coco caramelizado",
    "Frutas cristalizadas"
  ]
};

export default mergedCatalogData;