const mergedCatalogData = {
  "Grãos": [
    "Amaranto",
    "Amêndoa",
    "Arroz Negro Granel",
    "Arroz Vermelho Granel",
    "Aveia Farelo Granel",
    "Aveia Farinha Granel",
    "Aveia Flocos Finos Granel",
    "Aveia Flocos Grossos Granel",
    "Avelã",
    "Avelã Granel",
    "Café em grão",
    "Café em grão Verde",
    "Chia Grão",
    "Ervilha Inteira",
    "Ervilha Partida",
    "Feijão Azuki",
    "Feijão Moyashi",
    "Feno Grego",
    "Funghi Seco",
    "Gergelim Branco",
    "Gergelim Preto",
    "Grão de bico",
    "Lentilha",
    "Lentilha Amarela",
    "Lentilha Beluga",
    "Lentilha Vermelha",
    "Linhaça Dourada",
    "Linhaça Marrom",
    "Milho Espanhol Mel e Mostarda",
    "Mix Gergelim",
    "Mix Quinoa",
    "Nibs de Cacau",
    "Noz da Casca",
    "Noz Mariposa",
    "Pepita de Abóbora",
    "Pepita de Abóbora c/sal",
    "Pepita de Girassol",
    "Pepita de Girassol c/sal",
    "Quinoa Branca",
    "Quinoa Preta",
    "Quinoa Vermelha",
    "Sagu",
    "Shitake",
    "Soja em Grão",
    "Tapioca Granulada"
  ],
  "Temperos": [
    "Alho Desidratado",
    "Alho em Pó",
    "Alho Frito",
    "Alho Roxo Cabeça",
    "Ajinomoto",
    "Amaciante de Carne",
    "Anis Estrelado",
    "Caldo de Picanha",
    "Caldo de Vegetais",
    "Canela em Pau",
    "Canela em Pó",
    "Cebola em Pó",
    "Cebola em Tiras",
    "Chilli",
    "Chimichurry com Alho Frito",
    "Chimichurry s/ Pimenta",
    "Chimigaletto",
    "Chipotle",
    "Colorau",
    "Cominho em Grão",
    "Cominho Moído",
    "Cominho Moído com Pimenta",
    "Curry",
    "Curry Temperado",
    "Dry Rub",
    "Fit Frango",
    "Fit Peixe",
    "Flor de Sal",
    "Garam Masala",
    "Gelatina sem Sabor",
    "Gotas de Chocolate ao Leite",
    "Lemon Pepper",
    "Lemon Pepper Defumado",
    "Noz Moscada",
    "Páprica Defumada",
    "Páprica Doce",
    "Páprica Picante",
    "Pimenta Caiena",
    "Pimenta do Reino Moída",
    "Pimenta do Reino Preta",
    "Tempero Baiano",
    "Tempero de Feijoada",
    "Tempero do Chef",
    "Tempero Paulista",
    "Tempero Sirio",
    "Tempero Zathar"
  ],
  "Ervas": [
    "Alecrim",
    "Amora Miura",
    "Amora Muira",
    "Anis Estrelado Quebrado",
    "Artemisia",
    "Boldo Granel",
    "Camomila",
    "Capim Santo",
    "Cardamomo",
    "Catuaba em Pó",
    "Cravo da Índia",
    "Cravo da Moído",
    "Chá Verde",
    "Coentro Grão",
    "Coentro Moído",
    "Clorella em Pó",
    "Curcuma",
    "Cravo de Índia",
    "Dente de Leão",
    "Erva Doce Pó",
    "Ervas Finas",
    "Espinheira Santa",
    "Gengibre em Pó",
    "Hibisco Flor",
    "Hortelã",
    "Louro",
    "Louro Pó",
    "Manjericão",
    "Manjerona",
    "Orégano Granel",
    "Passiflora",
    "Seca Barriga",
    "Salsa",
    "Tomilho",
    "Uxi"
  ],
  "Petiscos": [
    "Amendoim Cru com Casca",
    "Amendoim Torrado com Casca",
    "Amendoim Runner",
    "Amendoim Doce",
    "Amendoim Japonês Cebola e Salsa",
    "Amendoim Japonês Churrasco",
    "Amendoim Japonês Pimenta",
    "Amendoim Japonês Tradicional",
    "Amêndoa Defumada",
    "Amêndoa Laminada",
    "Amêndoas",
    "Blueberry Granel",
    "Cebola Crisp",
    "Cebola Granulada",
    "Granulada Roxa em Flocos",
    "Chips de Banana",
    "Chips de Batata Doce",
    "Chips de Coco (sem açúcar)",
    "Chips de Macaxeira",
    "Chips de Macaxeira Defumada",
    "Chips de Macaxeira com Lemon Pepper",
    "Chips de Provolone",
    "Chips de Provolone com Goiaba",
    "Chips de Queijo Coalho",
    "Chips de Queijo Reino",
    "Chips de Queijo Coalho com Nutella",
    "Chips de Queijo Coalho com Goiaba",
    "Cranberry",
    "Damasco",
    "Ervilha com Wasabi",
    "Fava Torrada com Mel e Mostarda",
    "Granola com Banana",
    "Granola Diet",
    "Granola Tradicional",
    "Laranja Desidratada",
    "Mix Nuts",
    "Pistache com Casca",
    "Pistache sem Casca",
    "Tâmara Jumbo",
    "Tâmara sem Caroço"
  ],
  "Beleza e Saúde": [
    "Açaí em Pó",
    "Agar Agar",
    "Albumina",
    "Camu Camu",
    "Colágeno Hidrolisado",
    "Creatina Monohidratada",
    "Clorella em Pó",
    "Eritritol",
    "Ginko Biloba",
    "Ginseng",
    "Goma Xantana",
    "Guaraná em Pó",
    "Leite de Coco Pó Vegano",
    "Levedura Nutricional",
    "Levedo de Cerveja",
    "Maca Peruana",
    "Spirulina",
    "Tribulus Terrestre",
  ],
  "Farinhas": [
    "Açúcar de Coco Importado",
    "Cacau em Pó",
    "Cacau Black",
    "Farinha de Amêndoa",
    "Farinha de Arroz Branca",
    "Farinha de Banana",
    "Farinha de Batata Doce",
    "Farinha de Beterraba",
    "Farinha de Castanha",
    "Farinha de Chia",
    "Farinha de Coco",
    "Farinha de Grão de Bico",
    "Farinha de Linhaça Dourada",
    "Farinha de Linhaça Marrom",
    "Farinha de Maçã",
    "Farinha de Maracujá",
    "Farinha de Quinoa",
    "Farinha de Uva",
    "Xilitol" 
  ],
};

export default mergedCatalogData;